name: Inject CA certs into crypto-config

on:
  workflow_dispatch:

jobs:
  inject-certs:
    runs-on: ubuntu-latest
    env:
      ISSUER_CA_CERT_B64: ${{ secrets.ISSUER_CA_CERT_B64 }}
      GREENSTAND_CA_TLS_CERT_B64: ${{ secrets.GREENSTAND_CA_TLS_CERT_B64 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create nested folders and inject certs
        run: |
          mkdir -p crypto-config/greenstand-ca
          mkdir -p crypto-config/ca

          echo "$ISSUER_CA_CERT_B64" | base64 -d > crypto-config/greenstand-ca/issuer-ca-cert.pem
          echo "$GREENSTAND_CA_TLS_CERT_B64" | base64 -d > crypto-config/ca/greenstand-ca-tls-cert.pem

          chmod 600 crypto-config/greenstand-ca/issuer-ca-cert.pem
          chmod 600 crypto-config/ca/greenstand-ca-tls-cert.pem
